send_downlink:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: akenza
          multiple: true
    payload:
      example: '{"targetTemperature": 21}'
      selector:
        object:
    payload_hex:
      example: "0e14"
      selector:
        text:
    port:
      default: 1
      selector:
        number:
          min: 1
          max: 223
          mode: box
    confirmed:
      default: false
      selector:
        boolean:
    topic:
      example: "downlink"
      selector:
        text:
